version: '3.3'
services:
  web:
    image: mbellgb/omnidash-dev # assumes image is on docker hub
    ports:
      - "80:3000"
    build:
      dockerfile: ./Dockerfile
    command: ["sh", "run-dev.sh"]
    environment:
      - RAILS_ENV=development

