version: "3.3"
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"

  nginx-gen:
    container_name: nginx-gen
    build:
      context: ./
      dockerfile: Dockerfile.nginx-gen
    restart: always
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - ACME_TOS_HASH=${ACME_TOS_HASH}

  web:
    image: mbellgb/omnidash-prod # assumes image is on docker hub
    container_name: web
    restart: always
    expose:
      - "3000"
    env_file:
      - ".env"
    build:
      dockerfile: ./Dockerfile
    command: ["sh", "run-prod.sh"]
    environment:
      - RAILS_ENV=production
      - VIRTUAL_HOST=${SITE_HOSTNAME}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${SITE_HOSTNAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  certs:
